package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of course.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CourseModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** course_No. */
	private String courseNo;

	/** course_Name. */
	private String courseName;
	
	private Integer teacherNo;
	private String semName;

	/** tuto_Percentage. */
	private Integer tutoPercentage;

	/** lab_Percentage. */
	private Integer labPercentage;

	/** assign_Percentage. */
	private Integer assignPercentage;

	/** exam_Percentage. */
	private Integer examPercentage;

	private Integer tutoGiven;
	private Integer assignGiven;
	private Integer labGiven;
	private Integer examGiven;
	
	/** teacher. */
	private TeacherModel teacher;

	/** semester. */
	private SemesterModel semester;

	/** The set of studentmark. */
	private Set<StudentmarkModel> studentmarkSet;

	/** The set of timetable. */
	private Set<TimetableModel> timetableSet;

	/**
	 * Constructor.
	 */
	public CourseModel() {
		this.studentmarkSet = new HashSet<StudentmarkModel>();
		this.timetableSet = new HashSet<TimetableModel>();
	
	}

	/**
	 * Set the course_No.
	 * 
	 * @param courseNo
	 *            course_No
	 */
	public void setCourseNo(String courseNo) {
		this.courseNo = courseNo;
	}

	/**
	 * Get the course_No.
	 * 
	 * @return course_No
	 */
	public String getCourseNo() {
		return this.courseNo;
	}

	/**
	 * Set the course_Name.
	 * 
	 * @param courseName
	 *            course_Name
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/**
	 * Get the course_Name.
	 * 
	 * @return course_Name
	 */
	public String getCourseName() {
		return this.courseName;
	}

	/**
	 * Set the tuto_Percentage.
	 * 
	 * @param tutoPercentage
	 *            tuto_Percentage
	 */
	public Integer getTeacherNo() {
		return teacherNo;
	}

	public void setTeacherNo(Integer teacherNo) {
		this.teacherNo = teacherNo;
	}
	public String getSemName() {
		return semName;
	}

	public void setSemName(String semName) {
		this.semName = semName;
	}

	public void setTutoPercentage(Integer tutoPercentage) {
		this.tutoPercentage = tutoPercentage;
	}

	/**
	 * Get the tuto_Percentage.
	 * 
	 * @return tuto_Percentage
	 */
	public Integer getTutoPercentage() {
		return this.tutoPercentage;
	}

	/**
	 * Set the lab_Percentage.
	 * 
	 * @param labPercentage
	 *            lab_Percentage
	 */
	public void setLabPercentage(Integer labPercentage) {
		this.labPercentage = labPercentage;
	}

	/**
	 * Get the lab_Percentage.
	 * 
	 * @return lab_Percentage
	 */
	public Integer getLabPercentage() {
		return this.labPercentage;
	}

	/**
	 * Set the assign_Percentage.
	 * 
	 * @param assignPercentage
	 *            assign_Percentage
	 */
	public void setAssignPercentage(Integer assignPercentage) {
		this.assignPercentage = assignPercentage;
	}

	/**
	 * Get the assign_Percentage.
	 * 
	 * @return assign_Percentage
	 */
	public Integer getAssignPercentage() {
		return this.assignPercentage;
	}

	/**
	 * Set the exam_Percentage.
	 * 
	 * @param examPercentage
	 *            exam_Percentage
	 */
	public void setExamPercentage(Integer examPercentage) {
		this.examPercentage = examPercentage;
	}

	/**
	 * Get the exam_Percentage.
	 * 
	 * @return exam_Percentage
	 */
	public Integer getExamPercentage() {
		return this.examPercentage;
	}

	public Integer getTutoGiven() {
		return tutoGiven;
	}

	public void setTutoGiven(Integer tutoGiven) {
		this.tutoGiven = tutoGiven;
	}

	public Integer getAssignGiven() {
		return assignGiven;
	}

	public void setAssignGiven(Integer assignGiven) {
		this.assignGiven = assignGiven;
	}

	public Integer getLabGiven() {
		return labGiven;
	}

	public void setLabGiven(Integer labGiven) {
		this.labGiven = labGiven;
	}

	public Integer getExamGiven() {
		return examGiven;
	}

	public void setExamGiven(Integer examGiven) {
		this.examGiven = examGiven;
	}

	/**
	 * Set the teacher.
	 * 
	 * @param teacher
	 *            teacher
	 */
	public void setTeacher(TeacherModel teacher) {
		this.teacher = teacher;
	}

	/**
	 * Get the teacher.
	 * 
	 * @return teacher
	 */
	public TeacherModel getTeacher() {
		return this.teacher;
	}

	/**
	 * Set the semester.
	 * 
	 * @param semester
	 *            semester
	 */
	public void setSemester(SemesterModel semester) {
		this.semester = semester;
	}

	/**
	 * Get the semester.
	 * 
	 * @return semester
	 */
	public SemesterModel getSemester() {
		return this.semester;
	}

	/**
	 * Set the set of the studentmark.
	 * 
	 * @param studentmarkSet
	 *            The set of studentmark
	 */
	public void setStudentmarkSet(Set<StudentmarkModel> studentmarkSet) {
		this.studentmarkSet = studentmarkSet;
	}

	/**
	 * Add the studentmark.
	 * 
	 * @param studentmark
	 *            studentmark
	 */
	public void addStudentmark(StudentmarkModel studentmark) {
		this.studentmarkSet.add(studentmark);
	}

	/**
	 * Get the set of the studentmark.
	 * 
	 * @return The set of studentmark
	 */
	public Set<StudentmarkModel> getStudentmarkSet() {
		return this.studentmarkSet;
	}

	/**
	 * Set the set of the timetable.
	 * 
	 * @param timetableSet
	 *            The set of timetable
	 */
	public void setTimetableSet(Set<TimetableModel> timetableSet) {
		this.timetableSet = timetableSet;
	}

	/**
	 * Add the timetable.
	 * 
	 * @param timetable
	 *            timetable
	 */
	public void addTimetable(TimetableModel timetable) {
		this.timetableSet.add(timetable);
	}

	/**
	 * Get the set of the timetable.
	 * 
	 * @return The set of timetable
	 */
	public Set<TimetableModel> getTimetableSet() {
		return this.timetableSet;
	}

	
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((courseNo == null) ? 0 : courseNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CourseModel other = (CourseModel) obj;
		if (courseNo == null) {
			if (other.courseNo != null) {
				return false;
			}
		} else if (!courseNo.equals(other.courseNo)) {
			return false;
		}
		return true;
	}

}
