package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of room.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** room_No. */
	private Integer roomNo;

	/** room_Name. */
	private String roomName;

	/** The set of timetable. */
	private Set<TimetableModel> timetableSet;

	/**
	 * Constructor.
	 */
	public RoomModel() {
		this.timetableSet = new HashSet<TimetableModel>();
	}

	/**
	 * Set the room_No.
	 * 
	 * @param roomNo
	 *            room_No
	 */
	public void setRoomNo(Integer roomNo) {
		this.roomNo = roomNo;
	}

	/**
	 * Get the room_No.
	 * 
	 * @return room_No
	 */
	public Integer getRoomNo() {
		return this.roomNo;
	}

	/**
	 * Set the room_Name.
	 * 
	 * @param roomName
	 *            room_Name
	 */
	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	/**
	 * Get the room_Name.
	 * 
	 * @return room_Name
	 */
	public String getRoomName() {
		return this.roomName;
	}

	/**
	 * Set the set of the timetable.
	 * 
	 * @param timetableSet
	 *            The set of timetable
	 */
	public void setTimetableSet(Set<TimetableModel> timetableSet) {
		this.timetableSet = timetableSet;
	}

	/**
	 * Add the timetable.
	 * 
	 * @param timetable
	 *            timetable
	 */
	public void addTimetable(TimetableModel timetable) {
		this.timetableSet.add(timetable);
	}

	/**
	 * Get the set of the timetable.
	 * 
	 * @return The set of timetable
	 */
	public Set<TimetableModel> getTimetableSet() {
		return this.timetableSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((roomNo == null) ? 0 : roomNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoomModel other = (RoomModel) obj;
		if (roomNo == null) {
			if (other.roomNo != null) {
				return false;
			}
		} else if (!roomNo.equals(other.roomNo)) {
			return false;
		}
		return true;
	}

}
