package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of semester.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SemesterModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sem_Name. */
	private String semName;

	/** noOf_Course. */
	private Integer noofCourse;

	/** The set of course. */
	private Set<CourseModel> courseSet;

	/** The set of studentmark. */
	private Set<StudentmarkModel> studentmarkSet;

	/** The set of timetable. */
	private Set<TimetableModel> timetableSet;

	/**
	 * Constructor.
	 */
	public SemesterModel() {
		this.courseSet = new HashSet<CourseModel>();
		this.studentmarkSet = new HashSet<StudentmarkModel>();
		this.timetableSet = new HashSet<TimetableModel>();
	}

	/**
	 * Set the sem_Name.
	 * 
	 * @param semName
	 *            sem_Name
	 */
	public void setSemName(String semName) {
		this.semName = semName;
	}

	/**
	 * Get the sem_Name.
	 * 
	 * @return sem_Name
	 */
	public String getSemName() {
		return this.semName;
	}

	/**
	 * Set the noOf_Course.
	 * 
	 * @param noofCourse
	 *            noOf_Course
	 */
	public void setNoofCourse(Integer noofCourse) {
		this.noofCourse = noofCourse;
	}

	/**
	 * Get the noOf_Course.
	 * 
	 * @return noOf_Course
	 */
	public Integer getNoofCourse() {
		return this.noofCourse;
	}

	/**
	 * Set the set of the course.
	 * 
	 * @param courseSet
	 *            The set of course
	 */
	public void setCourseSet(Set<CourseModel> courseSet) {
		this.courseSet = courseSet;
	}

	/**
	 * Add the course.
	 * 
	 * @param course
	 *            course
	 */
	public void addCourse(CourseModel course) {
		this.courseSet.add(course);
	}

	/**
	 * Get the set of the course.
	 * 
	 * @return The set of course
	 */
	public Set<CourseModel> getCourseSet() {
		return this.courseSet;
	}

	/**
	 * Set the set of the studentmark.
	 * 
	 * @param studentmarkSet
	 *            The set of studentmark
	 */
	public void setStudentmarkSet(Set<StudentmarkModel> studentmarkSet) {
		this.studentmarkSet = studentmarkSet;
	}

	/**
	 * Add the studentmark.
	 * 
	 * @param studentmark
	 *            studentmark
	 */
	public void addStudentmark(StudentmarkModel studentmark) {
		this.studentmarkSet.add(studentmark);
	}

	/**
	 * Get the set of the studentmark.
	 * 
	 * @return The set of studentmark
	 */
	public Set<StudentmarkModel> getStudentmarkSet() {
		return this.studentmarkSet;
	}

	/**
	 * Set the set of the timetable.
	 * 
	 * @param timetableSet
	 *            The set of timetable
	 */
	public void setTimetableSet(Set<TimetableModel> timetableSet) {
		this.timetableSet = timetableSet;
	}

	/**
	 * Add the timetable.
	 * 
	 * @param timetable
	 *            timetable
	 */
	public void addTimetable(TimetableModel timetable) {
		this.timetableSet.add(timetable);
	}

	/**
	 * Get the set of the timetable.
	 * 
	 * @return The set of timetable
	 */
	public Set<TimetableModel> getTimetableSet() {
		return this.timetableSet;
	}


}
