package com.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of student.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StudentModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** student_No. */
	private Integer studentNo;

	/** user. */
	private UserModel user;
	private Integer userNo;

	/** address. */
	private String address;

	/** ph_No. */
	private String phNo;

	/** birth_Date. */
	private Date birthDate;

	/** guardian. */
	private String guardian;

	/** batch. */
	private Integer batch;

	/** The set of rollno. */
	private Set<RollnoModel> rollnoSet;

	/** The set of studentmark. */
	private Set<StudentmarkModel> studentmarkSet;

	/** The set of tutorial. */
	private Set<TutorialModel> tutorialSet;

	/**
	 * Constructor.
	 */
	public StudentModel() {
		this.rollnoSet = new HashSet<RollnoModel>();
		this.studentmarkSet = new HashSet<StudentmarkModel>();
		this.tutorialSet = new HashSet<TutorialModel>();
	}

	/**
	 * Set the student_No.
	 * 
	 * @param studentNo
	 *            student_No
	 */
	public void setStudentNo(Integer studentNo) {
		this.studentNo = studentNo;
	}

	/**
	 * Get the student_No.
	 * 
	 * @return student_No
	 */
	public Integer getStudentNo() {
		return this.studentNo;
	}

	/**
	 * Set the user.
	 * 
	 * @param user
	 *            user
	 */
	public void setUser(UserModel user) {
		this.user = user;
	}

	/**
	 * Get the user.
	 * 
	 * @return user
	 */
	public UserModel getUser() {
		return this.user;
	}

	public Integer getUserNo() {
		return userNo;
	}

	public void setUserNo(Integer userNo) {
		this.userNo = userNo;
	}

	/**
	 * Set the address.
	 * 
	 * @param address
	 *            address
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * Get the address.
	 * 
	 * @return address
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * Set the ph_No.
	 * 
	 * @param phNo
	 *            ph_No
	 */
	public void setPhNo(String phNo) {
		this.phNo = phNo;
	}

	/**
	 * Get the ph_No.
	 * 
	 * @return ph_No
	 */
	public String getPhNo() {
		return this.phNo;
	}

	/**
	 * Set the birth_Date.
	 * 
	 * @param birthDate
	 *            birth_Date
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * Get the birth_Date.
	 * 
	 * @return birth_Date
	 */
	public Date getBirthDate() {
		return this.birthDate;
	}

	/**
	 * Set the guardian.
	 * 
	 * @param guardian
	 *            guardian
	 */
	public void setGuardian(String guardian) {
		this.guardian = guardian;
	}

	/**
	 * Get the guardian.
	 * 
	 * @return guardian
	 */
	public String getGuardian() {
		return this.guardian;
	}

	/**
	 * Set the batch.
	 * 
	 * @param batch
	 *            batch
	 */
	public void setBatch(Integer batch) {
		this.batch = batch;
	}

	/**
	 * Get the batch.
	 * 
	 * @return batch
	 */
	public Integer getBatch() {
		return this.batch;
	}

	/**
	 * Set the set of the rollno.
	 * 
	 * @param rollnoSet
	 *            The set of rollno
	 */
	public void setRollnoSet(Set<RollnoModel> rollnoSet) {
		this.rollnoSet = rollnoSet;
	}

	/**
	 * Add the rollno.
	 * 
	 * @param rollno
	 *            rollno
	 */
	public void addRollno(RollnoModel rollno) {
		this.rollnoSet.add(rollno);
	}

	/**
	 * Get the set of the rollno.
	 * 
	 * @return The set of rollno
	 */
	public Set<RollnoModel> getRollnoSet() {
		return this.rollnoSet;
	}

	/**
	 * Set the set of the studentmark.
	 * 
	 * @param studentmarkSet
	 *            The set of studentmark
	 */
	public void setStudentmarkSet(Set<StudentmarkModel> studentmarkSet) {
		this.studentmarkSet = studentmarkSet;
	}

	/**
	 * Add the studentmark.
	 * 
	 * @param studentmark
	 *            studentmark
	 */
	public void addStudentmark(StudentmarkModel studentmark) {
		this.studentmarkSet.add(studentmark);
	}

	/**
	 * Get the set of the studentmark.
	 * 
	 * @return The set of studentmark
	 */
	public Set<StudentmarkModel> getStudentmarkSet() {
		return this.studentmarkSet;
	}

	/**
	 * Set the set of the tutorial.
	 * 
	 * @param tutorialSet
	 *            The set of tutorial
	 */
	public void setTutorialSet(Set<TutorialModel> tutorialSet) {
		this.tutorialSet = tutorialSet;
	}

	/**
	 * Add the tutorial.
	 * 
	 * @param tutorial
	 *            tutorial
	 */
	public void addTutorial(TutorialModel tutorial) {
		this.tutorialSet.add(tutorial);
	}

	/**
	 * Get the set of the tutorial.
	 * 
	 * @return The set of tutorial
	 */
	public Set<TutorialModel> getTutorialSet() {
		return this.tutorialSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((studentNo == null) ? 0 : studentNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		StudentModel other = (StudentModel) obj;
		if (studentNo == null) {
			if (other.studentNo != null) {
				return false;
			}
		} else if (!studentNo.equals(other.studentNo)) {
			return false;
		}
		return true;
	}

}
