package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of teacher.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TeacherModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** teacher_No. */
	private Integer teacherNo;

	/** user. */
	private UserModel user;

	/** permission_TimeTable. */
	private Boolean permissionTimetable;

	/** permission_StuInfo. */
	private Boolean permissionStuinfo;

	/** The set of course. */
	private Set<CourseModel> courseSet;

	/** The set of timetable. */
	private Set<TimetableModel> timetableSet;

	/**
	 * Constructor.
	 */
	public TeacherModel() {
		this.courseSet = new HashSet<CourseModel>();
		this.timetableSet = new HashSet<TimetableModel>();
	}

	/**
	 * Set the teacher_No.
	 * 
	 * @param teacherNo
	 *            teacher_No
	 */
	public void setTeacherNo(Integer teacherNo) {
		this.teacherNo = teacherNo;
	}

	/**
	 * Get the teacher_No.
	 * 
	 * @return teacher_No
	 */
	public Integer getTeacherNo() {
		return this.teacherNo;
	}

	/**
	 * Set the user.
	 * 
	 * @param user
	 *            user
	 */
	public void setUser(UserModel user) {
		this.user = user;
	}

	/**
	 * Get the user.
	 * 
	 * @return user
	 */
	public UserModel getUser() {
		return this.user;
	}

	/**
	 * Set the permission_TimeTable.
	 * 
	 * @param permissionTimetable
	 *            permission_TimeTable
	 */
	public void setPermissionTimetable(Boolean permissionTimetable) {
		this.permissionTimetable = permissionTimetable;
	}

	/**
	 * Get the permission_TimeTable.
	 * 
	 * @return permission_TimeTable
	 */
	public Boolean getPermissionTimetable() {
		return this.permissionTimetable;
	}

	/**
	 * Set the permission_StuInfo.
	 * 
	 * @param permissionStuinfo
	 *            permission_StuInfo
	 */
	public void setPermissionStuinfo(Boolean permissionStuinfo) {
		this.permissionStuinfo = permissionStuinfo;
	}

	/**
	 * Get the permission_StuInfo.
	 * 
	 * @return permission_StuInfo
	 */
	public Boolean getPermissionStuinfo() {
		return this.permissionStuinfo;
	}

	/**
	 * Set the set of the course.
	 * 
	 * @param courseSet
	 *            The set of course
	 */
	public void setCourseSet(Set<CourseModel> courseSet) {
		this.courseSet = courseSet;
	}

	/**
	 * Add the course.
	 * 
	 * @param course
	 *            course
	 */
	public void addCourse(CourseModel course) {
		this.courseSet.add(course);
	}

	/**
	 * Get the set of the course.
	 * 
	 * @return The set of course
	 */
	public Set<CourseModel> getCourseSet() {
		return this.courseSet;
	}

	/**
	 * Set the set of the timetable.
	 * 
	 * @param timetableSet
	 *            The set of timetable
	 */
	public void setTimetableSet(Set<TimetableModel> timetableSet) {
		this.timetableSet = timetableSet;
	}

	/**
	 * Add the timetable.
	 * 
	 * @param timetable
	 *            timetable
	 */
	public void addTimetable(TimetableModel timetable) {
		this.timetableSet.add(timetable);
	}

	/**
	 * Get the set of the timetable.
	 * 
	 * @return The set of timetable
	 */
	public Set<TimetableModel> getTimetableSet() {
		return this.timetableSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((teacherNo == null) ? 0 : teacherNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TeacherModel other = (TeacherModel) obj;
		if (teacherNo == null) {
			if (other.teacherNo != null) {
				return false;
			}
		} else if (!teacherNo.equals(other.teacherNo)) {
			return false;
		}
		return true;
	}

}
