package com.model;

import java.io.Serializable;

/**
 * Model class of timetable.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TimetableModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sem_No. */
	private Integer semNo;

	/** semester. */
	private SemesterModel semester;

	/** time. */
	private TimeModel time;

	/** teacher. */
	private TeacherModel teacher;

	/** course. */
	private CourseModel course;

	/** room. */
	private RoomModel room;

	/**
	 * Constructor.
	 */
	public TimetableModel() {
	}

	/**
	 * Set the sem_No.
	 * 
	 * @param semNo
	 *            sem_No
	 */
	public void setSemNo(Integer semNo) {
		this.semNo = semNo;
	}

	/**
	 * Get the sem_No.
	 * 
	 * @return sem_No
	 */
	public Integer getSemNo() {
		return this.semNo;
	}

	/**
	 * Set the semester.
	 * 
	 * @param semester
	 *            semester
	 */
	public void setSemester(SemesterModel semester) {
		this.semester = semester;
	}

	/**
	 * Get the semester.
	 * 
	 * @return semester
	 */
	public SemesterModel getSemester() {
		return this.semester;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(TimeModel time) {
		this.time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public TimeModel getTime() {
		return this.time;
	}

	/**
	 * Set the teacher.
	 * 
	 * @param teacher
	 *            teacher
	 */
	public void setTeacher(TeacherModel teacher) {
		this.teacher = teacher;
	}

	/**
	 * Get the teacher.
	 * 
	 * @return teacher
	 */
	public TeacherModel getTeacher() {
		return this.teacher;
	}

	/**
	 * Set the course.
	 * 
	 * @param course
	 *            course
	 */
	public void setCourse(CourseModel course) {
		this.course = course;
	}

	/**
	 * Get the course.
	 * 
	 * @return course
	 */
	public CourseModel getCourse() {
		return this.course;
	}

	/**
	 * Set the room.
	 * 
	 * @param room
	 *            room
	 */
	public void setRoom(RoomModel room) {
		this.room = room;
	}

	/**
	 * Get the room.
	 * 
	 * @return room
	 */
	public RoomModel getRoom() {
		return this.room;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((semNo == null) ? 0 : semNo.hashCode());
		result = prime * result + ((time == null) ? 0 : time.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TimetableModel other = (TimetableModel) obj;
		if (semNo == null) {
			if (other.semNo != null) {
				return false;
			}
		} else if (!semNo.equals(other.semNo)) {
			return false;
		}
		if (time == null) {
			if (other.time != null) {
				return false;
			}
		} else if (!time.equals(other.time)) {
			return false;
		}
		return true;
	}

}
