package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of time.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TimeModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** time_Id. */
	private Integer timeId;

	/** day. */
	private String day;

	/** time. */
	private Integer time;

	/** The set of timetable. */
	private Set<TimetableModel> timetableSet;

	/**
	 * Constructor.
	 */
	public TimeModel() {
		this.timetableSet = new HashSet<TimetableModel>();
	}

	/**
	 * Set the time_Id.
	 * 
	 * @param timeId
	 *            time_Id
	 */
	public void setTimeId(Integer timeId) {
		this.timeId = timeId;
	}

	/**
	 * Get the time_Id.
	 * 
	 * @return time_Id
	 */
	public Integer getTimeId() {
		return this.timeId;
	}

	/**
	 * Set the day.
	 * 
	 * @param day
	 *            day
	 */
	public void setDay(String day) {
		this.day = day;
	}

	/**
	 * Get the day.
	 * 
	 * @return day
	 */
	public String getDay() {
		return this.day;
	}

	/**
	 * Set the time.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(Integer time) {
		this.time = time;
	}

	/**
	 * Get the time.
	 * 
	 * @return time
	 */
	public Integer getTime() {
		return this.time;
	}

	/**
	 * Set the set of the timetable.
	 * 
	 * @param timetableSet
	 *            The set of timetable
	 */
	public void setTimetableSet(Set<TimetableModel> timetableSet) {
		this.timetableSet = timetableSet;
	}

	/**
	 * Add the timetable.
	 * 
	 * @param timetable
	 *            timetable
	 */
	public void addTimetable(TimetableModel timetable) {
		this.timetableSet.add(timetable);
	}

	/**
	 * Get the set of the timetable.
	 * 
	 * @return The set of timetable
	 */
	public Set<TimetableModel> getTimetableSet() {
		return this.timetableSet;
	}


}
