package com.model;

import java.io.Serializable;

/**
 * Model class of tutorial.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TutorialModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** student. */
	private StudentModel student;

	/** course. */
	private CourseModel course;

	/** tuto1. */
	private Integer tuto1;

	/** tuto2. */
	private Integer tuto2;

	/** tuto3. */
	private Integer tuto3;

	/** tuto4. */
	private Integer tuto4;

	/** tuto5. */
	private Integer tuto5;

	/**
	 * Constructor.
	 */
	public TutorialModel() {
	}

	/**
	 * Set the student.
	 * 
	 * @param student
	 *            student
	 */
	public void setStudent(StudentModel student) {
		this.student = student;
	}

	/**
	 * Get the student.
	 * 
	 * @return student
	 */
	public StudentModel getStudent() {
		return this.student;
	}

	/**
	 * Set the course.
	 * 
	 * @param course
	 *            course
	 */
	public void setCourse(CourseModel course) {
		this.course = course;
	}

	/**
	 * Get the course.
	 * 
	 * @return course
	 */
	public CourseModel getCourse() {
		return this.course;
	}

	/**
	 * Set the tuto1.
	 * 
	 * @param tuto1
	 *            tuto1
	 */
	public void setTuto1(Integer tuto1) {
		this.tuto1 = tuto1;
	}

	/**
	 * Get the tuto1.
	 * 
	 * @return tuto1
	 */
	public Integer getTuto1() {
		return this.tuto1;
	}

	/**
	 * Set the tuto2.
	 * 
	 * @param tuto2
	 *            tuto2
	 */
	public void setTuto2(Integer tuto2) {
		this.tuto2 = tuto2;
	}

	/**
	 * Get the tuto2.
	 * 
	 * @return tuto2
	 */
	public Integer getTuto2() {
		return this.tuto2;
	}

	/**
	 * Set the tuto3.
	 * 
	 * @param tuto3
	 *            tuto3
	 */
	public void setTuto3(Integer tuto3) {
		this.tuto3 = tuto3;
	}

	/**
	 * Get the tuto3.
	 * 
	 * @return tuto3
	 */
	public Integer getTuto3() {
		return this.tuto3;
	}

	/**
	 * Set the tuto4.
	 * 
	 * @param tuto4
	 *            tuto4
	 */
	public void setTuto4(Integer tuto4) {
		this.tuto4 = tuto4;
	}

	/**
	 * Get the tuto4.
	 * 
	 * @return tuto4
	 */
	public Integer getTuto4() {
		return this.tuto4;
	}

	/**
	 * Set the tuto5.
	 * 
	 * @param tuto5
	 *            tuto5
	 */
	public void setTuto5(Integer tuto5) {
		this.tuto5 = tuto5;
	}

	/**
	 * Get the tuto5.
	 * 
	 * @return tuto5
	 */
	public Integer getTuto5() {
		return this.tuto5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((student == null) ? 0 : student.hashCode());
		result = prime * result + ((course == null) ? 0 : course.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		TutorialModel other = (TutorialModel) obj;
		if (student == null) {
			if (other.student != null) {
				return false;
			}
		} else if (!student.equals(other.student)) {
			return false;
		}
		if (course == null) {
			if (other.course != null) {
				return false;
			}
		} else if (!course.equals(other.course)) {
			return false;
		}
		return true;
	}

}
