package com.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserModel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_No. */
	private Integer userNo;

	/** user_Name. */
	private String userName;

	/** user_Password. */
	private String userPassword;

	/** user_Type. */
	private String userType;

	/** The set of student. */
	private Set<StudentModel> studentSet;

	/** The set of teacher. */
	private Set<TeacherModel> teacherSet;

	/**
	 * Constructor.
	 */
	public UserModel() {
		this.studentSet = new HashSet<StudentModel>();
		this.teacherSet = new HashSet<TeacherModel>();
	}

	/**
	 * Set the user_No.
	 * 
	 * @param userNo
	 *            user_No
	 */
	public void setUserNo(Integer userNo) {
		this.userNo = userNo;
	}

	/**
	 * Get the user_No.
	 * 
	 * @return user_No
	 */
	public Integer getUserNo() {
		return this.userNo;
	}

	/**
	 * Set the user_Name.
	 * 
	 * @param userName
	 *            user_Name
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * Get the user_Name.
	 * 
	 * @return user_Name
	 */
	public String getUserName() {
		return this.userName;
	}

	/**
	 * Set the user_Password.
	 * 
	 * @param userPassword
	 *            user_Password
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	/**
	 * Get the user_Password.
	 * 
	 * @return user_Password
	 */
	public String getUserPassword() {
		return this.userPassword;
	}

	/**
	 * Set the user_Type.
	 * 
	 * @param userType
	 *            user_Type
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * Get the user_Type.
	 * 
	 * @return user_Type
	 */
	public String getUserType() {
		return this.userType;
	}

	/**
	 * Set the set of the student.
	 * 
	 * @param studentSet
	 *            The set of student
	 */
	public void setStudentSet(Set<StudentModel> studentSet) {
		this.studentSet = studentSet;
	}

	/**
	 * Add the student.
	 * 
	 * @param student
	 *            student
	 */
	public void addStudent(StudentModel student) {
		this.studentSet.add(student);
	}

	/**
	 * Get the set of the student.
	 * 
	 * @return The set of student
	 */
	public Set<StudentModel> getStudentSet() {
		return this.studentSet;
	}

	/**
	 * Set the set of the teacher.
	 * 
	 * @param teacherSet
	 *            The set of teacher
	 */
	public void setTeacherSet(Set<TeacherModel> teacherSet) {
		this.teacherSet = teacherSet;
	}

	/**
	 * Add the teacher.
	 * 
	 * @param teacher
	 *            teacher
	 */
	public void addTeacher(TeacherModel teacher) {
		this.teacherSet.add(teacher);
	}

	/**
	 * Get the set of the teacher.
	 * 
	 * @return The set of teacher
	 */
	public Set<TeacherModel> getTeacherSet() {
		return this.teacherSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userNo == null) ? 0 : userNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserModel other = (UserModel) obj;
		if (userNo == null) {
			if (other.userNo != null) {
				return false;
			}
		} else if (!userNo.equals(other.userNo)) {
			return false;
		}
		return true;
	}

}
